version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
  web:
    build: .
    image: jorgedjr21/work_time_management
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment: 
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306
      - BUNDLE_PATH=/bundle/vendor
    volumes:
      - .:/work_time_management
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_path:
  mysql-db: